### ISSUE TITLE
fileNamePattern utc pattern not effect

### ISSUE THREAD

**Issue by idotools-xuqiang** [tony19/logback-android#112] opened 2016-03-17 08:51 UTC
Set the fileNamePattern of appender like this : aFolder/test.%d{yyyy-MM-dd-HH, UTC}.log
The UTC modifier is not effect.

**Comment by tstdum1** [comment] 2016-03-17 12:47
That feature isn't released in logback-android yet.

**Comment by tony19** [comment] 2022-11-06 18:44
I cannot reproduce this issue with `logback-android` 2.0.0 on Pixel 3 (API 33), using this config:

```xml
<configuration
    xmlns="https://tony19.github.io/logback-android/xml"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://tony19.github.io/logback-android/xml https://cdn.jsdelivr.net/gh/tony19/logback-android/logback.xsd"
    debug="true"
>
    <appender name="file" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <encoder>
            <pattern>[%-20thread] %msg</pattern>
        </encoder>
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <fileNamePattern>/data/data/com.example.myapplication/files/aFolder/test.%d{yyyy-MM-dd-HH, UTC}.log</fileNamePattern>
        </rollingPolicy>
    </appender>
    <appender name="logcat" class="ch.qos.logback.classic.android.LogcatAppender">
        <tagEncoder>
            <pattern>%logger{12}</pattern>
        </tagEncoder>
        <encoder>
            <pattern>[%-20thread] %msg</pattern>
        </encoder>
    </appender>
    <root level="TRACE">
        <appender-ref ref="file" />
        <appender-ref ref="logcat" />
    </root>
</configuration>
```

Logging to the `file` appender at this UTC time -- `2022-11-06T18:41:02.290Z` -- creates this file:

```
/data/data/com.example.myapplication/files/aFolder/test.2022-11-06-18.log
```

Note `18` in the filename corresponds to `HH` in the filename pattern, which is the hour at UTC.

Feel free to create a new issue if the problem resurfaces.

**Closed by tony19** 2022-11-06 18:44 UTC
Labels: bug, pinned
