### ISSUE TITLE
Logback doesn't create and write to a file in Android

### ISSUE THREAD

**Issue by dreemz17** [tony19/logback-android#235] opened 2022-01-29 20:23 UTC
Hi, 
I have installed logback in Android and configured it as follows:
```xml
<configuration debug='true'>
    <!-- Stop output INFO at start -->
    <statusListener class="ch.qos.logback.core.status.NopStatusListener" />
    <appender name="FILE" class="ch.qos.logback.core.FileAppender">
        <file>/data/data/com.*********/files/config/logs/Test.log</file>
        <encoder>
            <pattern>%d [%-5p] %c - %m%n</pattern>
        </encoder>
        <level>DEBUG</level>
    </appender>
    <appender name="CA" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d [%-5p] %c - %m%n</pattern>
        </encoder>
        <level>DEBUG</level>
    </appender>
    <logger name="com.********" level="error"/>
    <logger name="com.******" level="DEBUG" additivity="false">
        <appender-ref ref="CA" />
        <appender-ref ref="FILE" />
    </logger>
    <root level="DEBUG">
        <appender-ref ref="CA"/>
        <appender-ref ref="FILE" />
    </root>
</configuration>
```

**Console output:**
```
-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/data/app/
-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@9d75c1c - URL [jar:file:/data/app/
-INFO in ch.qos.logback.core.joran.action.StatusListenerAction - Added status listener of type [ch.qos.logback.core.status.NopStatusListener]
-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.FileAppender]
-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
-ERROR in ch.qos.logback.core.joran.spi.Interpreter@19:8 - no applicable action for [level], current ElementPath  is [[configuration][appender][level]]
-INFO in ch.qos.logback.core.FileAppender[FILE] - File property is set to [/data/data/com.*********/files/config/logs/Test.log]
-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [CA]
-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
-ERROR in ch.qos.logback.core.joran.spi.Interpreter@25:8 - no applicable action for [level], current ElementPath  is [[configuration][appender][level]]
-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.******] to ERROR
-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.*****] 
-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [com.******] to false
-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [CA]   to Logger[com.kpit.diagnostic.viessmann.android_test_application]
-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[com.kpit.diagnostic.viessmann.android_test_application]
-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to DEBUG
-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [CA] to Logger[ROOT]
-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
-INFO in ch.qos.logback.classic.joran.JoranConfigurator@f537c6 - Registering current configuration as safe fallback point
```

On running app, nothing happens and Test.log doesn't appear in App's data directory at the path mentioned "/data/data/com.*********/files/config/logs/Test.log" Any suggestions?

Environment:
Android 11

**Comment by tony19** [comment] 2022-02-03 23:27
I can't reproduce the problem. What code are you using to actually log something to the file? Can you share a link to a GitHub repo that reproduces the problem?

**Comment by dreemz17** [comment] 2022-02-07 06:57
I am able to create and write a file after application space folder"/data/data/com.*********/Test.log. But I want to create log file inside the already created subfolders in application space folder for ex: "/data/data/com.*********/files/config/logs/Test.log" .
Why the log file is not created inside subfolders?

**Comment by tony19** [comment] 2022-02-07 10:28
That works fine in my experiments. What does the debug log show? Can you share a link to a Github repo that reproduces the problem? Without a way to reproduce the problem, this issue will likely be closed.

**Comment by tony19** [comment] 2022-02-14 18:57
Closing due to lack of reproduction

**Closed by tony19** 2022-02-14 18:57 UTC
