### ISSUE TITLE
Gradle Error: more than one library with package name 'com.github.tony19'

### ISSUE THREAD

**Issue by schildbach** [tony19/logback-android#163] opened 2018-02-25 15:42 UTC
When upgrading from logback-android 1.1.1-6 to logback-android 1.1.1-8, I got this error from Gradle:

```
Execution failed for task ':wallet:processDebugResources'.
> Error: more than one library with package name 'com.github.tony19'
```

I had to exclude `group: 'com.github.tony19', module: 'apktool-lib'` from my build to get it working again.

**Comment by tony19** [comment] 2018-02-25 23:16
What command are you using to build? (I couldn't reproduce with `./gradlew assemble`).

Can you try `1.1.1-9-SNAPSHOT` from `https://oss.sonatype.org/content/repositories/snapshots`?

**Comment by schildbach** [comment] 2018-02-28 09:49
I used `gradle clean build`, but `gradle assemble` has got the same problem.

**Comment by schildbach** [comment] 2018-02-28 09:54
`https://oss.sonatype.org/content/repositories/snapshots/com/github/tony19/logback-android/1.1.1-9-SNAPSHOT/logback-android-1.1.1-9-20180225.231257-2.pom`fixes the problem.

**Comment by tony19** [comment] 2018-03-05 01:09
Fixed in [v_1.1.1-9](https://github.com/tony19/logback-android/releases/tag/v_1.1.1-9)

**Closed by tony19** 2018-03-05 01:09 UTC
