### ISSUE TITLE
Inside Gradle build causes android.jar download from MavenCentral/JCenter

### ISSUE THREAD

**Issue by paulvi** [tony19/logback-android#73] opened 2014-07-31 03:39 UTC
I have tried inside Gradle build with

```
compile group: 'com.github.tony19', name: 'logback-android-core', version: '1.1.1-3'
compile group: 'com.github.tony19', name: 'logback-android-classic', version: '1.1.1-3'
compile group: 'org.slf4j', name: 'slf4j-api', version: '1.7.6'
```

and got 

![err-gradle-logback](https://cloud.githubusercontent.com/assets/1614482/3759696/3bb75af0-1864-11e4-861c-a3e132d21f3a.PNG)

**Comment by altdeveloper** [comment] 2015-01-11 05:19
I can confirm that this is still happening.

**Comment by tony19** [comment] 2015-01-11 05:26
As a workaround, please try the following exclusion rule:

```
compile('com.github.tony19:logback-android-classic:1.1.1-3') {
    exclude group: 'com.google.android', module: 'android'
}
```

**Comment by altdeveloper** [comment] 2015-01-11 07:48
Thanks @tony19 . Works great.

**Comment by gspreder** [comment] 2017-11-02 21:51
When using the new 3.0.0 build system, this issue has now become a blocker.
When building Release (not Debug) builds, the build fails with this error (provided in full for search engines so people find this):

    Ill-advised or mistaken usage of a core class (java.* or javax.*)
    when not building a core library.
    This is often due to inadvertently including a core library file
    in your application's project, when using an IDE (such as
    Eclipse). If you are sure you're not intentionally defining a
    core class, then this is the most likely explanation of what's
    going on.
    However, you might actually be trying to define a class in a core
    namespace, the source of which you may have taken, for example,
    from a non-Android virtual machine project. This will most
    assuredly not work. At a minimum, it jeopardizes the
    compatibility of your app with future versions of the platform.
    It is also often of questionable legality.
    If you really intend to build a core library -- which is only
    appropriate as part of creating a full virtual machine
    distribution, as opposed to compiling an application -- then use
    the "--core-library" option to suppress this error message.
    If you go ahead and use "--core-library" but are in fact
    building an application, then be forewarned that your application
    will still fail to build or run, at some point. Please be
    prepared for angry customers who find, for example, that your
    application ceases to function once they upgrade their operating
    system. You will be to blame for this problem.
    If you are legitimately using some code that happens to be in a
    core package, then the easiest safe alternative you have is to
    repackage that code. That is, move the classes in question into
    your own package namespace. This means that they will never be in
    conflict with core system classes. JarJar is a tool that may help
    you in this endeavor. If you find that you cannot do this, then
    that is an indication that the path you are on will ultimately
    lead to pain, suffering, grief, and lamentation.

The workaround described here and your README.md solves the issue just the same. The impact is simply greater now.

**Comment by hardikpansuria** [comment] 2017-11-22 07:22
I have upgraded android Gradle plugin 3.0.0 then after getting same error 


Ill-advised or mistaken usage of a core class (java.* or javax.*)
when not building a core library.
This is often due to inadvertently including a core library file
in your application's project, when using an IDE (such as
Eclipse). If you are sure you're not intentionally defining a
core class, then this is the most likely explanation of what's
going on.
However, you might actually be trying to define a class in a core
namespace, the source of which you may have taken, for example,
from a non-Android virtual machine project. This will most
assuredly not work. At a minimum, it jeopardizes the
compatibility of your app with future versions of the platform.
It is also often of questionable legality.
If you really intend to build a core library -- which is only
appropriate as part of creating a full virtual machine
distribution, as opposed to compiling an application -- then use
the "--core-library" option to suppress this error message.
If you go ahead and use "--core-library" but are in fact
building an application, then be forewarned that your application
will still fail to build or run, at some point. Please be
prepared for angry customers who find, for example, that your
application ceases to function once they upgrade their operating
system. You will be to blame for this problem.
If you are legitimately using some code that happens to be in a
core package, then the easiest safe alternative you have is to
repackage that code. That is, move the classes in question into
your own package namespace. This means that they will never be in
conflict with core system classes. JarJar is a tool that may help
you in this endeavor. If you find that you cannot do this, then
that is an indication that the path you are on will ultimately
lead to pain, suffering, grief, and lamentation.



NOTE : getting error Only in Release not in Debug !!

**Comment by tony19** [comment] 2018-03-06 03:06
Fixed in [v_1.1.1-7](https://github.com/tony19/logback-android/releases/tag/v_1.1.1-7)

**Closed by tony19** 2018-03-06 03:06 UTC
