### ISSUE TITLE
RollingPolicy MaxHistory not deleting old files

### ISSUE THREAD

**Issue by AlexandrSalin** [tony19/logback-android#184] opened 2018-08-13 23:35 UTC
seems like it already fixed in 
https://jira.qos.ch/browse/LOGBACK-162

but doesn't work for android

my config 

  ```
        LoggerContext loggerContext = (LoggerContext) LoggerFactory.getILoggerFactory();
        loggerContext.reset();

        RollingFileAppender<ILoggingEvent> rollingFileAppender = new RollingFileAppender<>();
        rollingFileAppender.setContext(loggerContext);
        rollingFileAppender.setAppend(true);
        rollingFileAppender.setFile(logDirectory + File.separator + logFileName + ".log");

        SizeAndTimeBasedFNATP<ILoggingEvent> fileNamingPolicy = new SizeAndTimeBasedFNATP<>();
        fileNamingPolicy.setContext(loggerContext);
        fileNamingPolicy.setMaxFileSize(fileSizeKB + "KB");

        TimeBasedRollingPolicy<ILoggingEvent> rollingPolicy = new TimeBasedRollingPolicy<>();
        rollingPolicy.setContext(loggerContext);
        rollingPolicy.setFileNamePattern(logDirectory + File.separator + logFileName + ".%d{yyyy-MM-dd}.%i.log");
        rollingPolicy.setMaxHistory(historyLength);
        rollingPolicy.setTimeBasedFileNamingAndTriggeringPolicy(fileNamingPolicy);
        rollingPolicy.setParent(rollingFileAppender);  // parent and context required!
        rollingPolicy.start();

        PatternLayoutEncoder encoder = new PatternLayoutEncoder();
        encoder.setContext(loggerContext);
        encoder.setCharset(Charset.forName("UTF-8"));
        encoder.setPattern("%date %level [%thread] %msg%n");
        encoder.start();

        rollingFileAppender.setRollingPolicy(rollingPolicy);
        rollingFileAppender.setEncoder(encoder);
        rollingFileAppender.start();

        // add the newly created appenders to the root logger;
        // qualify Logger to disambiguate from org.slf4j.Logger
        ch.qos.logback.classic.Logger root = (ch.qos.logback.classic.Logger) LoggerFactory.getLogger(Logger.ROOT_LOGGER_NAME);
        root.setLevel(level);
        root.addAppender(rollingFileAppender);
```

**Comment by FilenkovMaxim** [comment] 2018-10-11 03:41
@tony19 in which moment logback performs deleting? Can you give me the name of this method?
Do I need to call something besides LoggerFactory.getLogger() in my code?

**Comment by tony19** [comment] 2018-10-11 05:05
The files are automatically deleted at startup (if configured with `cleanHistoryOnStart`) and on each log event (e.g., when `logger.info(...)` is called). For `TimeBasedRollingPolicy`, the rollover occurs in `TimeBasedRollingPolicy#rollover()`:

https://github.com/tony19/logback-android/blob/45c2dba2f5296c913b2b3f122751f190717fdbf4/logback-android/src/main/java/ch/qos/logback/core/rolling/TimeBasedRollingPolicy.java#L182

**Comment by AlexandrSalin** [comment] 2018-10-16 10:48
@tony19 , do you have any thoughts how we can fix the issue with programmatic config? the logic which setup logback placed in another module and used by several apps. i guess i can't just change it to xml

**Comment by FilenkovMaxim** [comment] 2018-10-22 09:12
@tony19 I can attach my full config if you can check it.

**Comment by FilenkovMaxim** [comment] 2018-11-08 08:22
@tony19 Hello! Have you any news on it?

**Comment by tony19** [comment] 2018-11-10 07:17
@FilenkovMaxim I think your example was intended for #191, as I see usage of `ContextInitializer` in the code. As I mentioned in that issue's [comments](https://github.com/tony19/logback-android/issues/191#issuecomment-433305879), `ContextInitializer.autoConfig` should not be invoked directly and is likely the cause of your problem.

**Comment by FilenkovMaxim** [comment] 2018-11-13 07:57
@tony19 I don't think that is related problems. I check RollingPolicy in this example without run resetLogs() method.
You can easy reproduce it following these steps:
run app, kill app, set system date next day
repeat this five times
check app folder /data/data/com.example.maxf.logbackexample/files/logs

**Comment by tony19** [comment] 2018-11-13 08:08
The daily rollover pattern is indeed related, as it's one way I can reproduce the problem of missed deletions. The rollover seems to work fine when using a second-based rollover pattern (`yyyyMMddss`) (a contrived but effective pattern for test purposes).

I have a simpler method of reproducing the issue. Add `<cleanHistoryOnStart>` to `TimeBasedRollingPolicy` XML config, create multiple files matching the filename pattern, and restart the app. At startup, the extra files should be deleted.

**Comment by FilenkovMaxim** [comment] 2018-11-13 08:10
@tony19 I meant #191 is not related to this issue

**Comment by tony19** [comment] 2018-11-13 09:19
Here's what's happening:

When a filename pattern contains two date patterns like this:

```xml
<rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
  <fileNamePattern>${LOG_DIR}/app.%d{yyyyMMdd}_%d{HHmmss,UTC}.log</fileNamePattern>
```

...the second date pattern (`%d{HHmmss,UTC}`) prevents `TimeBasedArchiveRemover` from finding expired files to delete. For instance, [`TimeBasedArchiveRemover#getFilesInPeriod()`](https://github.com/tony19/logback-android/blob/c5504c8/logback-android/src/main/java/ch/qos/logback/core/rolling/helper/TimeBasedArchiveRemover.java#L67) tries to find the following files (note the `060000` part):

```
/data/data/com.example.maxf.logbackexample/files/logs/app.20181110_060000.log
...
/data/data/com.example.maxf.logbackexample/files/logs/app.20181102_060000.log
/data/data/com.example.maxf.logbackexample/files/logs/app.20181101_060000.log
/data/data/com.example.maxf.logbackexample/files/logs/app.20181031_050000.log
...
/data/data/com.example.maxf.logbackexample/files/logs/app.20181022_050000.log
/data/data/com.example.maxf.logbackexample/files/logs/app.20181021_050000.log
/data/data/com.example.maxf.logbackexample/files/logs/app.20181020_050000.log
...
/data/data/com.example.maxf.logbackexample/files/logs/app.20181012_050000.log
/data/data/com.example.maxf.logbackexample/files/logs/app.20181011_050000.log
/data/data/com.example.maxf.logbackexample/files/logs/app.20181010_050000.log
```

...but the log files are actually named with nonzero times for the second timestamp like this:

    /data/data/com.example.maxf.logbackexample/files/logs/app.20181113_074601.log

**Comment by FilenkovMaxim** [comment] 2018-11-13 13:08
Thanks for finding the source of the issue, do you think you can fix it in the next few days?

**Comment by tony19** [comment] 2018-12-05 08:35
Fixed in [v_1.3.0-3](https://github.com/tony19/logback-android/releases/tag/v_1.3.0-3)

**Closed by tony19** 2018-12-05 08:35 UTC

**Comment by tony19** [comment] 2018-12-05 08:59
@AlexandrSalin I've verified the fix with your config in my [test app](https://github.com/tony19-sandbox/logback-test-app/blob/23da31a/app/src/main/java/com/example/logbackandroidtestapp/AsyncLogbackConfigurationTask.java#L45). Note that the solution implemented for [LOGBACK-162](https://jira.qos.ch/browse/LOGBACK-162) did not actually fix the problem in full, and had critical holes that would allow archive removals to be missed. I've refactored it in logback-android.

**Comment by tony19** [comment] 2018-12-05 09:15
@FilenkovMaxim Note your filename pattern contains multiple date specifiers, which prevents logback from finding the correct files to remove:

     ${LOG_DIR}/app.%d{yyyyMMdd}_%d{HHmmss,UTC}.log
                    ^^^^^^^^^^^^ ^^^^^^^^^^^^^^

Only one date specifier can be the "primary" one. The auxiliary ones must be marked with `aux` (see [docs](https://logback.qos.ch/manual/appenders.html#tbrpFileNamePattern)):

     ${LOG_DIR}/app.%d{yyyyMMdd,aux}_%d{HHmmss,UTC}.log

**Comment by FilenkovMaxim** [comment] 2018-12-05 09:31
@tony19 thank you for explanation, I've changed my config already.
P.S. I got the message Failed to resolve: com.github.tony19:logback-android:1.3.0-3
Seems too early try to download?

**Comment by tony19** [comment] 2018-12-05 09:36
I'm working on the release right now. You can [download it](https://github.com/tony19/logback-android/releases/download/v_1.3.0-3/logback-android-1.3.0-3.aar) manually in the meantime for local testing.

I also forgot to mention that when using multiple date specifiers, they all should have the same timezone. logback would still work, but it could be confusing for users to see two different timestamps in the filename. It should look like this:

    ${LOG_DIR}/app.%d{yyyyMMdd,UTC,aux}_%d{HHmmss,UTC}.log
