### ISSUE TITLE
Logs are not deleted after maxhistory days triggered

### ISSUE THREAD

**Issue by RohanPatel22** [tony19/logback-android#227] opened 2021-08-24 12:28 UTC
## Description
  We expected to delete all logs files after max history days passed. We have configured logback.xml correctly but didn't get result. 

  Please find logback.xml

            <fileNamePattern>logs/Debug.%d{yyyy-MM-dd}.log</fileNamePattern>

            
            <maxHistory>10</maxHistory>
            

        </rollingPolicy>

        <filter class="ch.qos.logback.classic.filter.LevelFilter">
            <level>DEBUG</level>
            <onMatch>ACCEPT</onMatch>
            <onMismatch>DENY</onMismatch>
        </filter>

        <encoder>
            <pattern>%-4relative,%d,%logger{35},%method,%line,[%thread],%level,%msg%n</pattern>
        </encoder>
    </appender>

    <appender name="INFO_TO_FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            
            <fileNamePattern>logs/Info.%d{yyyy-MM-dd}.log</fileNamePattern>

            
            <maxHistory>10</maxHistory>
            

        </rollingPolicy>

        <filter class="ch.qos.logback.classic.filter.LevelFilter">
            <level>INFO</level>
            <onMatch>ACCEPT</onMatch>
            <onMismatch>DENY</onMismatch>
        </filter>

        <encoder>
            <pattern>%-4relative,%d,%logger{35},%method,%line,[%thread],%level,%msg%n</pattern>
        </encoder>
    </appender>

    <appender name="WARN_AND_ABOVE_TO_FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            
            <fileNamePattern>logs/WarnError.%d{yyyy-MM-dd}.log</fileNamePattern>

            
            <maxHistory>10</maxHistory>
            

        </rollingPolicy>

        <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
            <level>WARN</level>
        </filter>

        <encoder>
            <pattern>%-4relative,%d,%logger{35},%method,%line,[%thread],%level,%msg%n</pattern>
        </encoder>
    </appender>

    <root level="TRACE">
        <appender-ref ref="DEBUG_TO_FILE" />
        <appender-ref ref="INFO_TO_FILE" />
        <appender-ref ref="WARN_AND_ABOVE_TO_FILE" />
    </root>
</configuration>
-->

## Environment

* **`logback-android` version:**
* **Android version:**
* **Platform:**

**Comment by tony19** [comment] 2021-11-07 03:50
Closing due to lack of reproduction

**Closed by tony19** 2021-11-07 03:50 UTC
Labels: bug
