### ISSUE TITLE
NPE in ThrowableProxy

### ISSUE THREAD

**Issue by bakua** [tony19/logback-android#200] opened 2019-07-26 07:44 UTC
## Description

I get reported below exception from some users when calling `org.slf4j.Logger#error(java.lang.String, java.lang.Throwable)`

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.StackTraceElement[].clone()' on a null object reference
       at ch.qos.logback.classic.spi.ThrowableProxy.()
       at ch.qos.logback.classic.spi.ThrowableProxy.()
       at ch.qos.logback.classic.spi.LoggingEvent.()
       at ch.qos.logback.classic.Logger.addAppender(Logger.java)
       at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java)
       at ch.qos.logback.classic.Logger.addAppender(Logger.java)
```

## Steps to reproduce

I don't know how to reproduce.

## Environment

* **`logback-android` version: 2.0.0**
* **Android version: So far 5.1 - 6.0.1**
* **Platform: any**

**Comment by tony19** [comment] 2019-08-24 19:13
I examined the code indicated in the stack trace, but nothing obvious stood out to me.

To help troubleshoot, can you provide the following?

 * the app source that shows the setup of `logback-android` and the logger that initiated the exception
 * the app itself (Google Play link or the apk)

**Comment by bakua** [comment] 2019-10-03 11:37
Hello, so I got back to this error and found, another library having the same issue: https://github.com/akaita/RxJava2Debug/issues/2

It is caused because of bug on Android 6.0.1 and lower. NPE happens when getting the stack trace:

https://android.googlesource.com/platform/libcore.git/+/android-4.2.2_r1/luni/src/main/java/java/lang/Throwable.java#201
https://android.googlesource.com/platform/libcore.git/+/android-6.0.1_r81/luni/src/main/java/java/lang/Throwable.java#264

The `nativeStackTrace()` native method returns null, causing the crash at `ch/qos/logback/classic/spi/ThrowableProxy.java:64`
```
this.stackTraceElementProxyArray = ThrowableProxyUtil.steArrayToStepArray(throwable
        .getStackTrace());
```

**Comment by bakua** [comment] 2019-12-10 08:29
@tony19 Are you sure this one should be closed? :)

**Comment by sebhard** [comment] 2020-02-28 17:10
Any progress on this?

**Comment by tony19** [comment] 2020-02-29 02:03
Looking into issue. The solution from RxJava2Debug doesn't seem to apply in our case, since our `Throwable` is passed in. I think we'll just have to`try-catch` the call.

**Comment by tony19** [comment] 2020-02-29 05:36
I'm not able to reproduce the bug in the emulator, so I can't test the fix. Do you have a way to reproduce this?

**Comment by bakua** [comment] 2020-03-01 12:46
I have actually never been able to reproduce the bug. But now I am using the following to get the stack trace and I don't get crashes anymore.

```
    public static StackTraceElement[] getSafeStackTrace(Throwable throwable) {
        try {
            return throwable.getStackTrace();
        } catch (NullPointerException ex) {
            return new StackTraceElement[0];
        }
    }
```

**Comment by ogkuzmin** [comment] 2020-05-11 15:41
Hello! 
In our project, we use your library. That's a nice tool, thank you very much. We got this problem described above. It can be easily reproduced. Try to log an instance of such exception: 

`class ExceptionWithoutStackTrace(message: String) : Exception(message) {
  override fun fillInStackTrace(): Throwable {
    return this
  }
}`

So we need to catch exception when getting a stack trace in ThrowableProxy constructor

**Comment by ogkuzmin** [comment] 2020-05-14 13:07
Also, there is a workaround with current versions of the library. In logback there is such entity like TurboFilter. It's a filter that used to define should we log this before the creation of ILoggingEvent (where the exception has occurred). So we can create a required version of TurboFilter and add it to logback through XML configuration file.

``` kotlin
class StackTraceFillFilter : TurboFilter() {
  override fun decide(
    marker: Marker?,
    logger: Logger?,
    level: Level?,
    format: String?,
    params: Array<out Any>?,
    t: Throwable?
  ): FilterReply {
    fixStackTraceFor(t)
    return FilterReply.NEUTRAL
  }

  private fun fixStackTraceFor(t: Throwable?) {
    if (t != null) {
      try {
        t.stackTrace
      } catch (e: Exception) {
        t.stackTrace = arrayOf()
      }
    }
  }
```

**Comment by tony19** [comment] 2022-11-06 04:15
Since this issue cannot be reproduced, I'm going to close this for now. Please create a new issue if the problem resurfaces.

**Closed** 2022-11-06 04:15 UTC
Labels: bug, cannot reproduce
