### ISSUE TITLE
The latest versions cannot be download from maven repos by Android Studio.

### ISSUE THREAD

**Issue by since2014** [tony19/logback-android#175] opened 2018-05-10 03:41 UTC

**Comment by tony19** [comment] 2018-05-10 04:27
I cannot reproduce this. The latest version is `1.1.1-11`. What version are you trying?

**Comment by tony19** [comment] 2018-05-11 01:38
Feel free to comment with steps to reproduce. I'll close this for now.

**Closed by tony19** 2018-05-11 01:38 UTC
